### PR TITLE
Update Versions

### PR DESCRIPTION
**Pull request by mariomurrent-softwaresolutions**

### CODE REVIEW

**Review by Gapur — APPROVED** [review]

**Comment by mariomurrent-softwaresolutions** [comment]
Should we maybe think about using any major version? Instead of specific versions?

**Comment by Gapur** [comment]
Oh I see you forked, so do you need access?

**Comment by mariomurrent-softwaresolutions** [comment]
The Fork is just temporarily 😊 would like to work on your repo

**Comment by Gapur** [comment]
Thanks. So you have a full access. Do you need anything? Please, let me know.

**Comment by mariomurrent-softwaresolutions** [comment]
Thank you very much.

**Pull request merged**
